# Spring Boot 공통 설정
spring:
  # 기본 활성 프로필 (로컬 개발용)
  profiles:
    active: prod
  
  # 애플리케이션 이름 설정
  application:
    name: pocamarket

  # JPA 공통 설정
  jpa:
    open-in-view: false
    hibernate:
      jdbc:
        batch_size: 1000
      naming:
        # 테이블명 대소문자 구분 설정
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Swagger 공통 설정
springdoc:
  # Swagger UI 접속 경로 커스텀
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    doc-expansion: none
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true

  # OpenAPI 문서 경로 커스텀
  api-docs:
    path: /v3/api-docs