# 프로덕션 환경용 설정
spring:
  # 외부 환경 변수 파일(.env) 지원
  config:
    import: optional:file:.env[.properties]

  # MariaDB 데이터소스 설정
  datasource:
    url: "jdbc:mariadb://${DB_URL:localhost}:${DB_PORT:3306}/${DB:pocamarket}"
    username: ${DB_USERNAME:pocauser}
    password: ${DB_PASSWORD:pocapassword}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      # 프로덕션용 커넥션 풀 설정
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000      # 5분
      max-lifetime: 1200000     # 20분
      connection-timeout: 20000 # 20초

  # JPA 프로덕션 설정
  jpa:
    hibernate:
      # 프로덕션에서는 스키마 변경 금지
      ddl-auto: none
    properties:
      hibernate:
        # 프로덕션에서는 SQL 로그 최소화
        show_sql: false
        format_sql: false
        use_sql_comments: false
        dialect: org.hibernate.dialect.MariaDBDialect

# JWT 프로덕션 설정 (보안 강화)
jwt:
  secret-key: ${JWT_SECRET_KEY:change-this-in-production}
  access-token-validity-in-ms: ${JWT_ACCESS_TOKEN_VALIDITY_MS:3600000}    # 1시간
  refresh-token-validity-in-ms: ${JWT_REFRESH_TOKEN_VALIDITY_MS:86400000} # 24시간

# 프로덕션용 Swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

# 프로덕션용 로깅 설정 (디버깅용으로 일시적 변경)
logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.type: warn
    com.venvas.pocamarket: info
    org.springframework.web: warn
    root: info

# 보안 설정
server:
  # 에러 정보 최소화
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never 