# Spring Boot 공통 설정
spring:
  # 기본 활성 프로필 (로컬 개발용)
  profiles:
    active: prod
  
  # 애플리케이션 이름 설정
  application:
    name: pocamarket

  # JPA 공통 설정
  jpa:
    open-in-view: false
    hibernate:
      jdbc:
        batch_size: 1000
      naming:
        # 테이블명 대소문자 구분 설정
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # Spring Security OAuth2 Client 설정
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope: name, email, nickname, profile_image
            redirect-uri: "https://pocamarket.co.kr/api/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            client-name: Naver
        
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

# Swagger 공통 설정
springdoc:
  # Swagger UI 접속 경로 커스텀
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    doc-expansion: none
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    url: /api/v3/api-docs # API 명세서 파일의 전체 경로를 알려주는 설정

  # OpenAPI 문서 경로 커스텀
  api-docs:
    path: /api/v3/api-docs

# OAuth2 소셜 로그인 설정
oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
    client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
    token-uri: https://oauth2.googleapis.com/token
    user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
    
  # 카카오 소셜 로그인 (추후 구현 시 사용)
  kakao:
    client-id: ${KAKAO_CLIENT_ID:your-kakao-client-id}
    client-secret: ${KAKAO_CLIENT_SECRET:your-kakao-client-secret}
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me