# AWS 환경 전용 설정 파일
spring:
  # 데이터소스 설정
  datasource:
    # AWS RDS MariaDB 접속 URL (환경 변수로 설정)
    url: "jdbc:mariadb://${DB_URL}:${DB_PORT}/${DB}"
    # 데이터베이스 사용자명 (환경 변수로 설정)
    username: ${DB_USERNAME}
    # 데이터베이스 비밀번호 (환경 변수로 설정)
    password: ${DB_PASSWORD}
    # JDBC 드라이버 설정
    driver-class-name: org.mariadb.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      # 데이터베이스 스키마 자동 업데이트
      # 개발 중에는 update, 프로덕션에서는 none으로 변경
      ddl-auto: none
      naming:
        # 테이블명 대소문자 구분 설정
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        # SQL 쿼리 로그 출력
        show_sql: true
        # SQL 포맷팅
        format_sql: true
        # SQL 쿼리에 주석 추가
        use_sql_comments: true

# 로깅 설정
logging:
  level:
    # Hibernate SQL 쿼리 로그 레벨
    org.hibernate.SQL: debug
    # 애플리케이션 로그 레벨
    com.venvas.pocamarket: debug
