spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: local
  application:
    name: web

  datasource:
    # jdbc:mariadb://[DB IP 주소]:[포트]/[db 이름]
    url: "jdbc:mariadb://${DB_URL}:${DB_PORT}/${DB}"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    #      naming:
    #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # 대소문자 구분
    properties:
      hibernate:
        #       show_sql: true
        format_sql: true
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace