# Spring Boot 기본 설정
spring:
  # 외부 환경 변수 파일(.env)에서 설정값을 읽어옴
  config:
    import: optional:file:.env[.properties]
  # 활성화된 프로필 설정 (AWS 환경)
  profiles:
    active: aws
  # 애플리케이션 이름 설정
  application:
    name: pocamarket

  # 데이터소스 설정
  datasource:
    # MariaDB 접속 URL (환경 변수로 설정)
    url: "jdbc:mariadb://${DB_URL}:${DB_PORT}/${DB}"
    # 데이터베이스 사용자명 (환경 변수로 설정)
    username: ${DB_USERNAME}
    # 데이터베이스 비밀번호 (환경 변수로 설정)
    password: ${DB_PASSWORD}
    # JDBC 드라이버 설정
    driver-class-name: org.mariadb.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      jdbc:
        batch_size: 1000
      # 데이터베이스 스키마 자동 업데이트
      ddl-auto: none
      naming:
        # 테이블명 대소문자 구분 설정
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        # SQL 쿼리 로그 출력
        show_sql: true
        # SQL 포맷팅
        format_sql: true
        # SQL 쿼리에 주석 추가
        use_sql_comments: true

# 로깅 설정
logging.level:
  # Hibernate SQL 쿼리 로그 레벨
  org.hibernate.SQL: debug
  # 애플리케이션 로그 레벨
  com.venvas.pocamarket: debug
  org.hibernate.type: trace

# JWT 설정
jwt:
  # JWT 서명에 사용할 비밀 키 (환경 변수에서 가져옴)
  secret-key: ${JWT_SECRET_KEY}
  # 액세스 토큰 유효 기간 (환경 변수에서 가져옴)
  access-token-validity-in-ms: ${JWT_ACCESS_TOKEN_VALIDITY_MS}
  # 리프레시 토큰 유효 기간 (환경 변수에서 가져옴)
  refresh-token-validity-in-ms: ${JWT_REFRESH_TOKEN_VALIDITY_MS}

# Swagger 설정
springdoc:
  # Swagger UI 접속 경로 커스텀 (기본: /swagger-ui/index.html)
  swagger-ui:
    path: /swagger-ui.html  # /swagger-ui.html로 접속 가능하게 함
    display-request-duration: true  # 요청-응답 시간 표시
    doc-expansion: none  # none, list, full (기본: none, 펼침 방식)
    operations-sorter: method  # 메서드명 기준 정렬(method, alpha 등)
    tags-sorter: alpha  # 태그 알파벳순 정렬
    try-it-out-enabled: true  # Try it out 버튼 기본 활성화

  # OpenAPI 문서 경로 커스텀 (기본: /v3/api-docs)
  api-docs:
    path: /v3/api-docs  # 기본값이지만, 필요시 변경 가능

  # 그룹별 문서 분리(멀티 API 문서 필요시)
  # group-configs:
  #   - group: v1
  #     paths-to-match: /api/v1/**
  #   - group: v2
  #     paths-to-match: /api/v2/**

  # 서버 정보 추가 (API 문서 내 서버 주소 표시)
  # servers:
  #   - url: https://api.pocamarket.com
  #     description: 실서버
  #   - url: http://localhost:8080
  #     description: 로컬 개발 서버

# Swagger 관련 보안 설정 예시 (Spring Security와 연동 시)
# spring.security:
#   ignored: /swagger-ui.html, /swagger-ui/**, /v3/api-docs/**, /swagger-resources/**